# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-08 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text=b'Name of the bank', max_length=255)),
            ],
            options={
                'db_table': 'bank',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('ifsc', models.CharField(help_text=b'IFSC code of branch', max_length=11, primary_key=True, serialize=False)),
                ('branch', models.CharField(help_text=b'Area of the branch is located', max_length=127)),
                ('address', models.CharField(help_text=b'Detailed address of the branch', max_length=195)),
                ('city', models.CharField(help_text=b'City where branch is located', max_length=50)),
                ('district', models.CharField(help_text=b'District where branch is located', max_length=50)),
                ('state', models.CharField(help_text=b'State in which branch is located', max_length=26)),
                ('bank', models.ForeignKey(help_text=b'FK to Bank table', on_delete=django.db.models.deletion.CASCADE, to='bank.Bank')),
            ],
            options={
                'db_table': 'branch',
            },
        ),
    ]
